# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do

desc "Run tests"
    lane :tests do
    run_tests(code_coverage:true,
        clean:true,
        project: "afazer.xcodeproj",
        devices: ["iPhone 5s"],
        scheme: "afazerUITests",
        slack_message:"Rodando os testes.",
        slack_url:"https://hooks.slack.com/services/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",
        slack_channel: "#general")

end

desc "Generate screenshots"
    lane :screenshots do
        capture_screenshots(scheme: "afazer")
        #upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
end

desc "Beta app"
    lane :beta do
        match(type: "development", readonly: true)
        increment_build_number(
            build_number: latest_testflight_build_number + 1,
            xcodeproj: "afazer.xcodeproj"
        )
        changelog = prompt(
            text: "Changelog: ",
            multi_line_end_keyword: "END"
        )
        build_app(scheme: "afazer",
            project: "afazer.xcodeproj",
            include_bitcode: true,
            export_method:"development"
        )
        upload_to_testflight(changelog: changelog)
end

error do |lane, exception|
    slack(
        slack_url:"https://hooks.slack.com/services/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",
        message: exception.message,
        success: false
    )
end

end
