# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

#.env.default
#SLACK_URL="https://hooks.slack.com/services/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"
#DELIVER_USERNAME = "brunoteixeiralc@gmail.com"
#DELIVER_APP_IDENTIFIER = "br.com.afazer"

update_fastlane

default_platform(:ios)

platform :ios do

desc "Run tests"
    lane :tests do
    run_tests(code_coverage:true,
        clean:true,
        project: "afazer.xcodeproj",
        devices: ["iPhone 5s"],
        scheme: "afazerUITests",
        slack_message:"Successfully run UI Tests")

end

desc "Generate screenshots and upload to apple store"
    lane :screenshots do
        capture_screenshots(scheme: "afazer")
        frame_screenshots(silver: true)
        upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
        slack(message:"Successfully uploaded screenshots to itunes connect", success:true)
end

desc "Beta app"
    lane :beta do
        match(type: "development", readonly: true)
        increment_build_number(
            build_number: latest_testflight_build_number + 1,
            xcodeproj: "afazer.xcodeproj"
        )
        changelog = prompt(
            text: "Changelog: ",
            multi_line_end_keyword: "END"
        )
        build_app(scheme: "afazer",
            clean:true,
            project: "afazer.xcodeproj",
            include_bitcode: true,
            export_method:"development"
        )
        upload_to_testflight(changelog: changelog)
        slack(message: "Successfully uploaded to Test Flight")
end

desc "Release app"
    lane :release do
        match(type: "distribution", readonly: true)
        build_app(scheme: "afazer",
            clean:true,
            project: "afazer.xcodeproj",
            include_bitcode: true,
            export_method:"app-store"
        )
        upload_to_app_store
        slack(message: "Successfully uploaded a new App Store build")
end

error do |lane, exception|
    slack(
        message: exception.message,
        success: false
    )
end

end
